/**
 * PRODUCTION WORD GENERATOR
 * Why this way?
 * 1. Tiered word lists: Monkeytype uses "English 200" (common) vs "English 1k" (advanced).
 * 2. Performance: O(n) selection using a modern Fisher-Yates shuffle variant or simple random sampling.
 * 3. Scalability: Easy to add "numbers", "punctuation", or "coding" modes later.
 */

const WORD_LISTS = {
  english: [
    "the", "be", "of", "and", "a", "to", "in", "he", "have", "it", "that", "for",
    "they", "with", "as", "not", "on", "she", "at", "by", "this", "we", "you",
    "do", "but", "from", "or", "which", "one", "would", "all", "will", "there",
    "say", "who", "make", "when", "can", "more", "if", "no", "man", "out", "other",
    "so", "what", "time", "up", "go", "about", "than", "into", "could", "state",
    "only", "new", "year", "some", "take", "come", "these", "know", "see", "use",
    "get", "like", "then", "first", "any", "work", "now", "may", "such", "give",
    "over", "think", "most", "even", "find", "day", "also", "after", "way", "many",
    "must", "look", "before", "great", "back", "through", "long", "where", "much",
    "should", "well", "people", "just", "because", "good", "each", "those", "feel",
    "seem", "how", "high", "too", "place", "little", "world", "very", "still", "nation",
    "hand", "old", "life", "tell", "write", "become", "here", "show", "house", "both",
    "between", "need", "mean", "call", "develop", "under", "last", "right", "move", "thing",
    "general", "school", "never", "same", "another", "begin", "while", "number", "part", "turn",
    "real", "leave", "might", "want", "point", "form", "off", "child", "few", "small",
    "since", "against", "ask", "late", "home", "interest", "large", "person", "end", "open",
    "public", "follow", "during", "present", "without", "again", "hold", "govern", "around",
    "possible", "head", "consider", "word", "program", "problem", "however", "lead", "system",
    "set", "order", "eye", "plan", "run", "keep", "face", "fact", "group", "play", "stand",
    "increase", "early", "course", "change", "help", "line",
    // Add 200+ words here for a real feel
    "able", "aboard", "above", "abroad", "absence", "absent", "absolute", "accept", "accident",
    "account", "achieve", "across", "act", "active", "actual", "add", "address", "admire",
    "admit", "adopt", "adult", "advance", "advantage", "advice", "advise", "affair", "affect",
    "afford", "afraid", "after", "afternoon", "afterwards", "again", "against", "age", "agency",
    "agenda", "ago", "agree", "ahead", "aim", "air", "airport", "alive", "all", "allow",
    "almost", "alone", "along", "already", "alright", "also", "although", "always", "among",
    "amount", "ancient", "and", "anger", "angle", "angry", "animal", "announce", "another",
    "answer", "anticipate", "anxiety", "any", "anybody", "anymore", "anyone", "anything",
    "anyway", "anywhere", "apart", "apartment", "apparent", "appeal", "appear", "apple",
    "apply", "appoint", "approach", "approve", "area", "argue", "arise", "arm", "army",
    "around", "arrange", "arrest", "arrive", "art", "article", "artist", "as", "ask",
    "aspect", "assemble", "assess", "asset", "assist", "assume", "assure", "at", "atmosphere",
    "attach", "attack", "attempt", "attend", "attention", "attitude", "attract", "audience",
    "author", "authority", "available", "average", "avoid", "award", "aware", "away", "awful",
    "baby", "back", "background", "bad", "bag", "balance", "ball", "band", "bank", "bar",
    "bare", "basic", "battle", "be", "beach", "bear", "beat", "beautiful", "because", "become",
    "bed", "bedroom", "beer", "before", "begin", "behind", "believe", "bell", "belong",
    "below", "beneath", "benefit", "beside", "best", "bet", "better", "between", "beyond",
    "big", "bike", "bill", "bird", "birth", "birthday", "bit", "bite", "black", "blame",
    "blank", "blind", "block", "blood", "blow", "blue", "board", "boat", "body", "bomb",
    "bond", "bone", "book", "boot", "border", "born", "borrow", "boss", "both", "bother",
    "bottle", "bottom", "box", "boy", "branch", "brave", "bread", "break", "breakfast",
    "breath", "breathe", "bridge", "brief", "bright", "bring", "broad", "broken", "brother",
    "brown", "brush", "buddy", "budget", "build", "building", "bullet", "bunch", "burn",
    "business", "busy", "but", "butter", "buy", "by", "cabin", "cable", "cake", "call",
    "calm", "camera", "camp", "campaign", "can", "cancel", "cancer", "candidate", "candle",
    "candy", "cap", "capable", "capacity", "capital", "captain", "car", "card", "care",
    "career", "careful", "careless", "carpet", "carry", "case", "cash", "catch", "category",
    "cause", "ceiling", "celebrate", "cell", "cent", "center", "central", "century",
    "certain", "certainly", "chain", "chair", "challenge", "champion", "chance", "change",
    "channel", "chapter", "character", "charge", "charity", "chart", "check", "cheek",
    "cheese", "chef", "chemical", "chest", "chicken", "chief", "child", "childhood",
    "chip", "chocolate", "choice", "choose", "church", "cigarette", "circle", "citizen",
    "city", "civil", "claim", "class", "clean", "clear", "clerk", "clever", "click",
    "client", "climate", "climb", "clock", "close", "closet", "cloth", "clothes",
    "clothing", "cloud", "club", "coach", "coal", "coast", "coat", "code", "coffee",
    "cold", "collect", "college", "color", "combine", "come", "comfort", "command",
    "comment", "commercial", "commission", "commit", "committee", "common", "communicate",
    "community", "company", "compare", "compete", "competition", "complete", "complex",
    "computer", "concentrate", "concept", "concern", "concert", "conclude", "condition",
    "conduct", "conference", "confidence", "confirm", "conflict", "confuse", "connect",
    "connection", "conscious", "consequence", "consider", "consist", "consistent",
    "constant", "construction", "contact", "contain", "contemporary", "content",
    "contest", "context", "continue", "contract", "contrast", "contribute", "control",
    "conversation", "convert", "convince", "cook", "cookie", "cool", "cooperate",
    "cope", "copy", "core", "corn", "corner", "correct", "cost", "cotton", "couch",
    "cough", "could", "council", "count", "counter", "country", "county", "couple",
    "courage", "course", "court", "cousin", "cover", "cow", "crack", "craft", "crash",
    "crazy", "cream", "create", "creative", "credit", "crew", "crime", "crisis",
    "critic", "critical", "crop", "cross", "crowd", "crucial", "cry", "cultural",
    "culture", "cup", "curious", "current", "curtain", "curve", "custom", "customer",
    "cut", "cycle", "dad", "daily", "damage", "dance", "danger", "dark", "date",
    "daughter", "day", "dead", "deal", "death", "debate", "debt", "decade", "decide",
    "decision", "declare", "decline", "deep", "defeat", "defend", "defense", "degree",
    "delay", "deliver", "demand", "democracy", "democrat", "demonstrate", "deny",
    "department", "depend", "deposit", "depression", "depth", "describe", "desert",
    "design", "desk", "desperate", "despite", "destroy", "detail", "detect", "develop",
    "development", "device", "devote", "dialogue", "die", "diet", "difference",
    "different", "difficult", "dig", "digital", "dimension", "dinner", "direct",
    "direction", "director", "dirt", "disappear", "disaster", "discipline", "discount",
    "discover", "discuss", "discussion", "disease", "dish", "dismiss", "display",
    "distance", "distinct", "district", "divide", "do", "doctor", "document", "dog",
    "door", "dot", "double", "doubt", "down", "downtown", "dozen", "draft", "drag",
    "drama", "draw", "dream", "dress", "drink", "drive", "drop", "drug", "drum",
    "dry", "due", "during", "dust", "duty", "each", "eager", "ear", "early", "earn",
    "earth", "ease", "east", "easy", "eat", "economic", "economy", "edge", "edit",
    "educate", "education", "effect", "effective", "efficient", "effort", "egg",
    "eight", "either", "elderly", "elect", "election", "electric", "element",
    "elevator", "else", "elsewhere", "embassy", "emerge", "emergency", "emotion",
    "emphasize", "employ", "employee", "employer", "empty", "enable", "encounter",
    "encourage", "end", "enemy", "energy", "engine", "engineering", "enjoy",
    "enormous", "enough", "ensure", "enter", "enterprise", "entertainment",
    "entire", "entrance", "entry", "environment", "episode", "equal", "equipment",
    "era", "error", "escape", "especially", "essay", "essential", "establish",
    "estimate", "even", "evening", "event", "eventually", "ever", "every",
    "everybody", "everyday", "everyone", "everything", "everywhere", "evidence",
    "evil", "exact", "exactly", "examine", "example", "excellent", "except",
    "exchange", "exciting", "exclude", "excuse", "execute", "exercise", "exhibit",
    "exist", "existence", "exit", "expand", "expect", "expense", "expensive",
    "experience", "experiment", "expert", "explain", "explode", "explore",
    "expose", "express", "expression", "extend", "extent", "external", "extra",
    "extreme", "eye", "face", "facility", "fact", "factor", "factory", "fail",
    "failure", "fair", "faith", "fall", "false", "familiar", "family", "famous",
    "fan", "fantasy", "far", "farm", "fashion", "fast", "fat", "father", "fault",
    "fear", "feature", "federal", "fee", "feed", "feel", "feeling", "female",
    "few", "field", "fight", "figure", "file", "fill", "film", "final", "finally",
    "finance", "find", "fine", "finger", "finish", "fire", "firm", "first",
    "fish", "fit", "five", "fix", "flag", "flame", "flat", "flavor", "flesh",
    "flight", "float", "floor", "flow", "flower", "fly", "focus", "fold",
    "follow", "food", "foot", "football", "for", "force", "foreign", "forest",
    "forever", "forget", "form", "formal", "former", "fortune", "forward",
    "found", "foundation", "four", "free", "freedom", "freeze", "frequent",
    "fresh", "friend", "friendly", "from", "front", "fruit", "fuel", "full",
    "fully", "fun", "function", "fund", "funny", "furniture", "further",
    "future", "gain", "game", "gap", "garage", "garden", "gas", "gate",
    "gather", "general", "generally", "generate", "generation", "gentleman",
    "get", "gift", "girl", "give", "glad", "glass", "global", "go", "goal",
    "god", "gold", "golden", "good", "government", "grab", "grade", "gradually",
    "graduate", "grain", "grand", "grandfather", "grandmother", "grant",
    "grass", "grave", "gray", "great", "green", "grocery", "ground", "group",
    "grow", "growth", "guarantee", "guard", "guess", "guest", "guide", "guilty",
    "gun", "guy", "habit", "hair", "half", "hall", "hand", "handle", "hang",
    "happen", "happy", "hard", "hardly", "hat", "hate", "have", "he", "head",
    "health", "healthy", "hear", "heart", "heat", "heavy", "hell", "hello",
    "help", "helpful", "her", "here", "herself", "hey", "hi", "hide", "high",
    "hill", "him", "himself", "his", "history", "hit", "hold", "hole", "holiday",
    "home", "honest", "hope", "horse", "hospital", "hot", "hotel", "hour",
    "house", "how", "however", "huge", "human", "humor", "hundred", "hungry",
    "hunt", "hurry", "hurt", "husband", "I", "ice", "idea", "ideal", "identify",
    "if", "ignore", "ill", "illegal", "image", "imagine", "immediate", "impact",
    "imply", "import", "important", "impose", "impossible", "impress", "improve",
    "in", "inch", "include", "including", "income", "increase", "indeed",
    "independent", "indicate", "individual", "industrial", "industry",
    "influence", "inform", "information", "inside", "insist", "instead",
    "institution", "instruction", "insurance", "intend", "interest",
    "interesting", "international", "interview", "into", "introduce",
    "invest", "investigate", "investment", "invite", "involve", "iron",
    "island", "issue", "it", "item", "its", "itself", "jacket", "job",
    "join", "joint", "joke", "judge", "judgment", "juice", "jump", "junior",
    "jury", "just", "justice", "keep", "key", "kick", "kid", "kill",
    "kind", "king", "kiss", "kitchen", "knee", "knife", "knock", "know",
    "knowledge", "lab", "lack", "ladder", "lady", "lake", "land", "landscape",
    "language", "large", "last", "late", "later", "laugh", "launch", "law",
    "lawyer", "lay", "layer", "lead", "leader", "leadership", "leading",
    "leaf", "league", "lean", "learn", "learning", "least", "leather",
    "leave", "lecture", "left", "leg", "legal", "legend", "legislation",
    "legitimate", "lemon", "length", "less", "lesson", "let", "letter",
    "level", "library", "lie", "life", "lift", "light", "like", "likely",
    "limit", "line", "link", "lip", "liquid", "list", "listen", "literature",
    "little", "live", "load", "loan", "local", "locate", "location", "lock",
    "log", "logic", "long", "look", "loop", "loose", "lose", "loss", "lost",
    "lot", "loud", "love", "lovely", "low", "luck", "lucky", "lunch",
    "machine", "mad", "magazine", "mail", "main", "maintain", "major",
    "majority", "make", "male", "mall", "man", "manage", "management",
    "manager", "manner", "manufacturer", "many", "map", "march", "mark",
    "market", "marriage", "married", "marry", "mask", "mass", "master",
    "match", "material", "math", "matter", "maximum", "may", "maybe",
    "mayor", "me", "meal", "mean", "meaning", "means", "measure", "meat",
    "media", "medical", "medicine", "medium", "meet", "meeting", "member",
    "memory", "mention", "menu", "mere", "merely", "mess", "message",
    "metal", "meter", "method", "middle", "midnight", "might", "military",
    "milk", "mind", "mine", "minimum", "minister", "minor", "minute",
    "miracle", "mirror", "miss", "mission", "mistake", "mix", "mixture",
    "mobile", "model", "modern", "modest", "mom", "moment", "money",
    "monitor", "month", "mood", "moon", "moral", "more", "morning",
    "most", "mostly", "mother", "motion", "motor", "mountain", "mouse",
    "mouth", "move", "movement", "movie", "Mr", "Mrs", "Ms", "much",
    "multiple", "murder", "muscle", "museum", "music", "musical", "must",
    "my", "myself", "mysterious", "nail", "name", "narrative", "narrow",
    "nation", "national", "native", "natural", "nature", "near", "nearly",
    "necessarily", "necessary", "neck", "need", "negative", "negotiate",
    "neighbor", "neighborhood", "neither", "nerve", "nervous", "net",
    "network", "never", "nevertheless", "new", "news", "newspaper", "next",
    "nice", "night", "no", "nobody", "noise", "none", "nor", "normal",
    "north", "northern", "nose", "not", "note", "nothing", "notice",
    "notion", "now", "nowhere", "nuclear", "number", "numerous", "nurse",
    "nut", "object", "objective", "obligation", "observation", "observe",
    "obtain", "obvious", "occasion", "occasionally", "occupation", "occupy",
    "occur", "ocean", "odd", "odds", "of", "off", "offense", "offensive",
    "offer", "office", "officer", "official", "often", "oh", "oil", "ok",
    "okay", "old", "on", "once", "one", "only", "onto", "open", "operate",
    "operation", "opinion", "opponent", "opportunity", "oppose", "opposite",
    "option", "or", "orange", "order", "ordinary", "organization", "organize",
    "orientation", "origin", "original", "other", "otherwise", "ought",
    "our", "ourselves", "out", "outcome", "outside", "oven", "over",
    "overall", "overcome", "overlook", "owe", "own", "owner", "pace",
    "pack", "package", "page", "pain", "paint", "painting", "pair",
    "pal", "pale", "palm", "pan", "panel", "pants", "paper", "parent",
    "park", "parliament", "part", "participant", "particular", "particularly",
    "partly", "partner", "party", "pass", "passage", "passenger", "passion",
    "past", "patch", "path", "patient", "pattern", "pause", "pay", "payment",
    "peace", "peak", "pen", "penalty", "pencil", "people", "pepper",
    "per", "perceive", "percentage", "perfect", "performance", "perhaps",
    "period", "permanent", "permission", "permit", "person", "personal",
    "personality", "personally", "perspective", "persuade", "pet", "phase",
    "philosophy", "phone", "photo", "photograph", "phrase", "physical",
    "piano", "pick", "picture", "pie", "piece", "pile", "pilot", "pin",
    "pink", "pipe", "pitch", "place", "plain", "plan", "plane", "planet",
    "plant", "plastic", "plate", "platform", "play", "player", "pleasant",
    "please", "pleasure", "plenty", "plot", "plus", "pocket", "poem",
    "poet", "poetry", "point", "pole", "police", "policy", "political",
    "politician", "politics", "poll", "pollution", "pool", "poor",
    "pop", "popular", "population", "porch", "port", "portion", "portrait",
    "position", "positive", "possess", "possibility", "possible", "possibly",
    "post", "pot", "potato", "potential", "pound", "pour", "poverty",
    "powder", "power", "practice", "praise", "pray", "prayer", "precisely",
    "predict", "prefer", "preference", "pregnancy", "pregnant", "preparation",
    "prepare", "prescription", "presence", "present", "presentation",
    "preserve", "president", "press", "pressure", "pretend", "pretty",
    "prevent", "previous", "previously", "price", "pride", "priest",
    "primarily", "primary", "prime", "principal", "principle", "print",
    "prior", "priority", "prison", "prisoner", "privacy", "private",
    "probably", "problem", "procedure", "proceed", "process", "produce",
    "product", "production", "profession", "professional", "professor",
    "profile", "profit", "program", "progress", "project", "promise",
    "promote", "prompt", "proof", "proper", "properly", "property",
    "proportion", "proposal", "propose", "prospect", "protect", "protection",
    "protest", "proud", "prove", "provide", "provider", "province",
    "provision", "psychological", "psychology", "public", "publication",
    "publicity", "publish", "pull", "punishment", "pupil", "purchase",
    "pure", "purpose", "pursue", "push", "put", "qualify", "quality",
    "quarter", "quarterback", "question", "quick", "quickly", "quiet",
    "quietly", "quit", "quite", "quote", "race", "racial", "radical",
    "radio", "rail", "rain", "raise", "range", "rank", "rapid", "rapidly",
    "rare", "rarely", "rate", "rather", "rating", "ratio", "raw", "reach",
    "react", "reaction", "read", "reader", "reading", "ready", "real",
    "reality", "realize", "really", "reason", "reasonable", "recall",
    "receive", "recent", "recently", "recipe", "recognition", "recognize",
    "recommend", "record", "recording", "recover", "red", "reduce",
    "reduction", "refer", "reference", "reflect", "reform", "refrigerator",
    "refuse", "regard", "region", "register", "regret", "regular",
    "regulate", "regulation", "reinforce", "reject", "relate", "relation",
    "relationship", "relative", "relatively", "relax", "release", "relevant",
    "relief", "religion", "religious", "rely", "remain", "remember",
    "remind", "remove", "repeat", "replace", "reply", "report", "reporter",
    "represent", "representation", "representative", "republic", "reputation",
    "request", "require", "requirement", "research", "resemble", "reservation",
    "resident", "resist", "resistance", "resolution", "resolve", "resort",
    "resource", "respect", "respond", "response", "responsibility",
    "responsible", "rest", "restaurant", "restore", "restrict", "result",
    "retain", "retire", "retirement", "return", "reveal", "revenue",
    "reverse", "review", "revolution", "reward", "rhythm", "rice", "rich",
    "rid", "ride", "rifle", "right", "ring", "rip", "rise", "risk",
    "river", "road", "rob", "rock", "role", "roll", "roof", "room",
    "root", "rope", "rose", "rough", "roughly", "round", "route", "routine",
    "row", "rub", "rule", "run", "rural", "rush", "sad", "safe", "safety",
    "sail", "sake", "salad", "salary", "sale", "salt", "same", "sample",
    "sand", "satellite", "satisfaction", "satisfy", "sauce", "save",
    "saving", "say", "scale", "scene", "schedule", "scheme", "school",
    "science", "scientific", "scientist", "scope", "score", "scratch",
    "screen", "screw", "script", "sea", "search", "season", "seat",
    "second", "secret", "secretary", "section", "sector", "secure",
    "security", "see", "seed", "seek", "seem", "segment", "select",
    "selection", "self", "sell", "senate", "senator", "send", "senior",
    "sense", "sensitive", "sentence", "separate", "sequence", "series",
    "serious", "serve", "service", "session", "set", "settle", "settlement",
    "seven", "several", "severe", "sex", "sexual", "shade", "shadow",
    "shake", "shall", "shape", "share", "sharp", "she", "sheet", "shelf",
    "shell", "shelter", "shift", "shine", "ship", "shirt", "shock",
    "shoe", "shoot", "shop", "shopping", "shore", "short", "shot",
    "should", "shoulder", "shout", "show", "shower", "shrug", "shut",
    "sick", "side", "sight", "sign", "signal", "signature", "significant",
    "silence", "silent", "silk", "silly", "silver", "similar", "simple",
    "simply", "since", "sing", "single", "sink", "sir", "sister", "sit",
    "site", "situation", "six", "size", "ski", "skill", "skin", "sky",
    "slave", "sleep", "slice", "slide", "slight", "slip", "slope",
    "slow", "slowly", "small", "smart", "smell", "smile", "smoke",
    "smooth", "snake", "snow", "so", "so-called", "soccer", "social",
    "society", "soft", "software", "soil", "solar", "soldier", "solid",
    "solution", "solve", "some", "somebody", "somehow", "someone",
    "something", "sometimes", "somewhat", "somewhere", "son", "song",
    "soon", "sophisticated", "sorry", "sort", "soul", "sound", "soup",
    "source", "south", "southern", "space", "speak", "special", "specialist",
    "species", "specific", "speech", "speed", "spell", "spend", "spending",
    "sphere", "spirit", "spiritual", "split", "spokesman", "sport",
    "spot", "spread", "spring", "square", "squeeze", "stability", "stable",
    "staff", "stage", "stair", "stake", "stand", "standard", "standing",
    "star", "stare", "start", "state", "statement", "station", "status",
    "stay", "steady", "steal", "steel", "step", "stick", "still", "stir",
    "stock", "stomach", "stone", "stop", "store", "storm", "story",
    "straight", "strange", "stranger", "strategic", "strategy", "stream",
    "street", "strength", "strengthen", "stress", "stretch", "strike",
    "string", "strip", "stroke", "strong", "structure", "struggle",
    "student", "studio", "study", "stuff", "stupid", "style", "subject",
    "submit", "subsequent", "substance", "substantial", "succeed",
    "success", "successful", "such", "sudden", "suddenly", "sue",
    "suffer", "sufficient", "sugar", "suggest", "suggestion", "suicide",
    "suit", "sum", "summer", "summit", "sun", "super", "supply", "support",
    "suppose", "sure", "surely", "surface", "surgery", "surprise",
    "surprised", "surprising", "surround", "survey", "survive", "suspect",
    "sustain", "swallow", "swear", "sweep", "sweet", "swim", "swing",
    "switch", "symbol", "sympathy", "system", "table", "tablespoon",
    "tactic", "tail", "take", "tale", "talent", "talk", "tall", "tape",
    "target", "task", "taste", "tax", "tea", "teach", "teacher", "teaching",
    "team", "tear", "teaspoon", "technical", "technique", "technology",
    "teen", "teenager", "telephone", "telescope", "television", "tell",
    "temperature", "temporary", "ten", "tend", "tendency", "tennis",
    "tension", "tent", "term", "terms", "terrible", "territory", "terror",
    "terrorist", "test", "testify", "testimony", "testing", "text",
    "than", "thank", "thanks", "that", "the", "theater", "their", "them",
    "theme", "themselves", "then", "theory", "there", "therefore", "these",
    "they", "thick", "thin", "thing", "think", "thinking", "third",
    "thirty", "this", "those", "though", "thought", "thousand", "threat",
    "threaten", "three", "throat", "through", "throughout", "throw",
    "thus", "ticket", "tie", "tight", "time", "tiny", "tip", "tire",
    "tired", "tissue", "title", "to", "tobacco", "today", "together",
    "tomorrow", "tone", "tongue", "tonight", "too", "took", "tool",
    "tooth", "top", "topic", "toss", "total", "totally", "touch",
    "tough", "tour", "tourist", "tournament", "toward", "towards",
    "tower", "town", "toy", "trace", "track", "trade", "tradition",
    "traditional", "traffic", "tragedy", "trail", "train", "training",
    "transfer", "transform", "transition", "translate", "transportation",
    "travel", "treat", "treatment", "treaty", "tree", "tremendous",
    "trend", "trial", "tribe", "trick", "trip", "troop", "trouble",
    "truck", "true", "truly", "trust", "truth", "try", "tube", "tunnel",
    "turn", "TV", "twelve", "twenty", "twice", "twin", "two", "type",
    "typical", "ugly", "ultimate", "ultimately", "umbrella", "unable",
    "uncle", "under", "undergo", "understand", "understanding", "unfortunately",
    "uniform", "union", "unique", "unit", "united", "universal", "universe",
    "university", "unknown", "unless", "unlike", "unlikely", "until",
    "unusual", "up", "upon", "upper", "urban", "urge", "us", "use",
    "used", "useful", "user", "usual", "usually", "vacation", "valley",
    "valuable", "value", "variety", "various", "vast", "vegetable",
    "vehicle", "venture", "version", "versus", "very", "vessel",
    "veteran", "via", "victim", "victory", "video", "view", "viewer",
    "village", "violate", "violation", "violence", "violent", "virtually",
    "virtue", "virus", "visible", "vision", "visit", "visitor", "visual",
    "vital", "voice", "volume", "volunteer", "vote", "voter", "vs",
    "vulnerable", "wage", "wait", "wake", "walk", "wall", "wander",
    "want", "war", "warm", "warn", "warning", "wash", "waste", "watch",
    "water", "wave", "way", "we", "weak", "wealth", "wealthy", "weapon",
    "wear", "weather", "web", "wedding", "week", "weekend", "weight",
    "weird", "welcome", "welfare", "well", "west", "western", "wet",
    "what", "whatever", "wheel", "when", "whenever", "where", "whereas",
    "wherever", "whether", "which", "while", "whisper", "white", "who",
    "whole", "whom", "whose", "why", "wide", "widely", "wife", "wild",
    "will", "willing", "win", "wind", "window", "wine", "wing", "winner",
    "winter", "wish", "with", "withdraw", "within", "without", "witness",
    "woman", "wonder", "wonderful", "wood", "wooden", "word", "work",
    "worker", "working", "works", "workshop", "world", "worried", "worry",
    "worth", "would", "wound", "wrap", "write", "writer", "writing",
    "wrong", "yard", "yeah", "year", "yell", "yellow", "yes", "yesterday",
    "yet", "yield", "you", "young", "your", "yours", "yourself", "youth",
    "zone"
  ],
  // code: ["const", "function", "return", "export", "import", "await", "async"],
};

/**
 * Generates a string of random words.
 * @param {number} limit - How many words to return.
 * @param {string} language - The dictionary to use.
 * @returns {string} - Space-separated words.
 */
export const generateWords = (limit = 25, language = "english") => {
  const list = WORD_LISTS[language] || WORD_LISTS.english;
  const result = [];

  for (let i = 0; i < limit; i++) {
    const randomIndex = Math.floor(Math.random() * list.length);
    result.push(list[randomIndex]);
  }

  // RETURN FORMAT: 
  // We return a string so the engine can treat the whole test as a single sequence 
  // of characters, which makes cursor calculation 100x easier.
  return result;
};